---
---
---

# ВВЕДЕНИЕ  {-}

География городов (геоурбанистика)
является комплексным научным направлением, объединяющим исследовательский аппарат географии, истории, экономики, обществознания. В России, где ¾ населения -- горожане, проблемы городов особенно актуальны, неслучайно они всё чаще привлекают внимание молодого поколения. С многими насущными проблемами городов школьники сталкиваются почти ежедневно, поэтому реализация практикума позволит проводить научные исследования на регулярной основе.

Настоящее руководство разработано для учителей географии образовательных учреждений, расположенных в городской местности, для проведения факультативных занятий по географии городов (геоурбанистике) с группами школьников, проявляющих повышенный интерес к географическим знаниям и исследованиям.

Практикум по геоурбанистике (географии городов), адаптирован для школьников и с учётом междисциплинарных связей географии городов с другими учебными предметами. Для учителей и учеников обеспечивается вариативность содержания индивидуальных задач и чёткое распределение ролей учащихся в коллективных исследованиях.

Пособие построено по принципу «конструктора»:
учитель может изменять содержание занятий в зависимости от возрастного состава и теоретической подготовленности группы школьников, доступного графика занятий, условий для полевых исследований, особенностей исследуемой местности, специфики
проблем территории дислокации школы, материального технической обеспеченности
исследований и т.д. В зависимости от размера и состава групп также можно существенно варьировать объёмом и видами детальности, комбинировать индивидуальную и коллективную работу, организовывать разделение видов деятельности, совместную работу школьников разного возраста.

Особое внимание при реализации программы практикума следует уделять организации практических исследований, особенно полевых наблюдений, в рамках которых требуется не только продуманная организация работ, но и соблюдение требований техники безопасности. Специальные инструкции по выполнению полевых работ приведены в соответствующих тематических разделах руководства.

В целом курс практических занятий рассчитан на 52 часа.

Примерное почасовое планирование приведено в ниже.

+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| №  | **Тематика**                                                                                                                                                                                                               | **Объём занятий, ч** |
+:==:+============================================================================================================================================================================================================================+:====================:+
| 1  | **Вводное занятие*.***Вводное занятие.                                                                                                                                                                                     | 6                    |
|    | Знакомство с методами изучения городской территории и источниками информации                                                                                                                                               |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 2  | **Историческая и природная среда**.                                                                                                                                                                                        | 6                    |
|    | Составление карты «Географическая летопись» поселения (городского района)                                                                                                                                                  |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 3  | **Внутригородское расселение.**                                                                                                                                                                                            | 6                    |
|    | Составление карты плотности населения поселения (городского района)                                                                                                                                                        |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 4  | **«Геометрия» города.**                                                                                                                                                                                                    | 4                    |
|    |                                                                                                                                                                                                                            |                      |
|    | Схема планировочной структуры города/городского района/населённого пункта                                                                                                                                                  |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 5  | **Транспорт в городе.**                                                                                                                                                                                                    | 5                    |
|    |                                                                                                                                                                                                                            |                      |
|    | Составление схем общественного транспорта (городские и сельские условия), картографический анализ проблем транспортной доступности (городские и сельские условия), концентрации личного автотранспорта (городские условия) |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 6  | **Функциональное зонирование городов.**                                                                                                                                                                                    | 5                    |
|    | Составление карт землепользования и анализ материалов функционального зонирования города/городского района/населённого пункта                                                                                              |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 7  | **Внутригородские миграции.**                                                                                                                                                                                              | 6                    |
|    |                                                                                                                                                                                                                            |                      |
|    | Составление схем движения (миграций) населения и сопоставление их со схемами общественного транспорта                                                                                                                      |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 8  | **Сфера обслуживания.**                                                                                                                                                                                                    | 5                    |
|    | Картирование предприятий сферы обслуживания и анализ принципов их размещения.                                                                                                                                              |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 9  | **Итоговый проект.**                                                                                                                                                                                                       | 9                    |
|    |                                                                                                                                                                                                                            |                      |
|    | Эссе на темы «Проблемы пространственное развитие городского района/поселения/ муниципального образования»,                                                                                                                 |                      |
|    |                                                                                                                                                                                                                            |                      |
|    | Сравнение с территориями-аналогами                                                                                                                                                                                         |                      |
+----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
