# Подготовка итогового проекта {#summary}


## Практическая часть

**Методические рекомендации для формулировки и выполнения задания:**

По итогам проведённых в течение учебного года исследований ученики под
руководством учителя готовят сводный отчёт о проведённых исследованиях.

В зависимости состава группы и от полученных в ходе курса результатов, итоговое
задание может быть реализовано в различных форматах:

- Индивидуальных исследовательских эссе по заданным темам;

- Серии индивидуальных или общего совместного доклада с электронной презентацией;

- Постера, отражающего суть проведённых исследований или посвящённого одной или нескольким ключевым
проблемам развития города и района.

Главная задача итогового проекта -- дать возможность участникам практикума вспомнить всё виды
исследований, выявить наиболее важные с их точки зрения.

**Исследовательское эссе** -- особый, творческий вид заданий. Школьникам необходимо напомнить о его структуре, форме написания и
при этом не ограничивать его стилистически. При подготовке тем эссе, которые предоставляются школьникам «на выбор» необходимо сформулировать их максимально привлекательно и «широко», оставаясь при этом в рамках геоурбанистики.
Примерами таких тем могут стать «Моё географическое открытие», «Неизвестное рядом...», «Если я был бы мэром...», «География моего района»...

При подготовке **доклада (докладов**) важно вместе с учениками найти общие, наиболее интересные и понравившиеся школьникам
сюжеты проведённых исследований, общую тему доклада важно также определить вместе. Задача учителя -- грамотно выстроить структур доклада, распределить роли учеников в его подготовке. В докладе должны присутствовать вводная часть, в которой формулируются главные задачи исследования, примеры из лекций, демонстрирующие теоретическую основу исследования, важно отразить наиболее
яркие моменты исследований. Самым главным в исследовательском докладе являются выводы. Их желательно формулировать сообща всем участникам проекта. Учителю в данном случае отводится роль редактора и модератора.

**Итоговый постер** -- одна из самых ярких и привлекательных форм завершающего вида деятельности. Она позволяет школьникам
систематизировать приобретённые навыки и полученные выводы. Рекомендуется подготовить итоговый постер под общим названием «Как мы исследуем родной город (наш район) и т.п.». При подготовке постера рекомендуется чётко выдерживать структуру представляемой информации. Как правило, постер содержит четыре раздела:

- Объект исследования (Характеристика город, района исследований)

- Методика исследований («Что мы делали?» и полученные отчётные и черновые материалы, в т.ч. карты)

- Ход исследований (фотографии выполняемых видов работ и исследуемой территории, отдельных объектов исследования)

- Основные результаты исследований (Полученные результаты и выводы)

При подготовке итоговых проектов важно ориентироваться на итоговую целевую направленность проекта. Как показывает опыт подобных исследований, они могут быть представлены на муниципальных, региональных конкурсах научного творчества,
в настенном оформлении кабинетов школ, кабинетов географии.




Приложение XXX.
Примеры функциональных зон городов на спутниковых снимках

Рисунок XXX. Селитебная зона. А --
индивидуальная; многоквартирная: Б -- малоэтажная, В -- среднеэтажная, Г --
многоэтажная, Д -- повышенной этажности, Е -- высотная

Источник: Google
Earth

Рисунок XXX.
Общественно-деловая зона: А -- административная и деловая, Б -- социальная (на
примере больниц); торговая зона: В -- рынки, Г -- торгово-развлекательные центры

Источник: Google
Earth

Рисунок XXX.
Производственная зона: А -- промышленная, Б -- складская; инфраструктурная зона:
В -- коммунальная (на примере водоочистных сооружений), Г -- транспортная (на
примере аэропорта)

Источник: Google Earth


Рисунок XXX.
Специальная зона: А -- на примере кладбищ, Б -- на примере воинских частей; рекреационная
зона: В -- зелёные зоны (на примере лесопарка), Г -- городские парки

Источник: Google Earth
